CREATE TABLE geb_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    full_name TEXT,
    password TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);