CREATE TABLE geb_grids(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES geb_users(id),
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    x TEXT NOT NULL,
    y TEXT NOT NULL,
    partial_transect_length INTEGER NOT NULL,
    x_partial TEXT NOT NULL,
    y_partial TEXT NOT NULL
)